package br.com.brunolopes.conciliacao.api.dto;

public enum CodigoErroApi {

    REQUISICAO_INVALIDA,
    CONCILIACAO_NAO_ENCONTRADA,
    RELATORIO_INDISPONIVEL,
    CONFLITO_DADOS,
    RESULTADO_INVALIDO,
    FALHA_COBOL,
    TIMEOUT_COBOL,
    CAPACIDADE_ESGOTADA,
    ERRO_INTERNO
}
